ALTER TABLE `User`
  MODIFY `googleId` VARCHAR(191) NULL,
  ADD COLUMN `provider` ENUM('LOCAL', 'GOOGLE') NOT NULL DEFAULT 'GOOGLE',
  ADD COLUMN `passwordHash` VARCHAR(191) NULL,
  ADD COLUMN `preferredLanguage` VARCHAR(191) NOT NULL DEFAULT 'ko';
